### ISSUE TITLE
请问公式为什么显示成乱码

### ISSUE THREAD

**Issue by jianzhang96** [wangjia184/diffusion_model#3]
您好，谢谢您的工作！
为什么我看到后面的公式都显示为乱码？
![image](https://github.com/wangjia184/diffusion_model/assets/31060586/f293b99e-2b4d-4e41-9004-5a48045b8af8)

**Comment by liwd190019** [comment]
There might be some issues in Github README.md rendering tool. All standalone equations that contain `\bar{}` can't be successfully displayed. To solve this, you can clone the project (or at least the README file if you don't want to download the dataset) and read the README on your local editor.
